name: 'Hello World'
description: 'Greet someone'
inputs:
  source-registry: # id of input
    description: 'Source-registry'
    required: true
    default: 'DockerHub'
  source-registry-loggin:
    description: 'Source-registry-loggin'
  source-registry-password:
    description: 'Source-registry-password'
outputs:
  random-number:
    description: 'Random number'
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: 'composite'
  steps:
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
